### ISSUE TITLE
GetWindowAbsolutePlacement is not enough.

### ISSUE THREAD

**Issue by ucyildirim** [micdenny/WpfScreenHelper#12]
Hi there.

Thank your the library.
Everything is working fine but there is one catch with the https://github.com/micdenny/WpfScreenHelper/blob/c15b29e08d0a65243a7d3af02324c54e91207d27/src/WpfScreenHelper/WindowHelper.cs#L45
This returns absolute position but, with my screen placement config, i need non-absolute results because i want to capture screetshot from each screen. To get the screenshot, i need the exact positon even it is below 0. 

Here is my screen placement.

**Windows settings**
++++++++++++++++++++++
|     SCREEN 1    |      SCREEN 2 (primary)   |
++++++++++++++++++++++

**Physical Placement**
++++++++++++++++++++++
|     **SCREEN 2**   |      SCREEN 1    |
++++++++++++++++++++++

Check the pr please.

Best regards.

**Comment by micdenny** [comment]
merged, thank you for the contribution

**Comment by micdenny** [comment]
published https://www.nuget.org/packages/WpfScreenHelper/2.1.0
