### ISSUE TITLE
WPFScreenHelper.NativeMethods is missing an initializer for NullHandleRef.

### ISSUE THREAD

**Issue by cpuwzd** [micdenny/WpfScreenHelper#2]
The corrected line should read:
public static readonly HandleRef NullHandleRef = new HandleRef(null, IntPtr.Zero);

**Comment by micdenny** [comment]
@cpuwzd can you open a PR for this? thank you

**Comment by micdenny** [comment]
in fact it's trivial, let me open it 😄
