### ISSUE TITLE
Quick start guide

### ISSUE THREAD

**Issue by DamianMorozov** [micdenny/WpfScreenHelper#8]
Where can I get a quick start guide?

**Comment by micdenny** [comment]
Originally I did the porting from the windows forms screen helper class, so most of the documentation can be taken from here: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.screen

Then some important changes has been made by @FoxPride that maybe could be so kind to create a wiki in this repo to show these changes, what are the differences from the old system.windows.forms.screen.

The quickstart could be the sample in the project that you can run https://github.com/micdenny/WpfScreenHelper/tree/master/test/WpfScreenHelper.DpiTestWpfApp

**Comment by FoxPride** [comment]
@micdenny please take a look at [wiki](https://github.com/micdenny/WpfScreenHelper/wiki) section. Hope it's enough for description.

**Comment by micdenny** [comment]
Thank you @FoxPride appreciated 🙇‍♂️
