### ISSUE TITLE
ScaleFactor bug

### ISSUE THREAD

**Issue by JonasEmilDamsgaard** [micdenny/WpfScreenHelper#9]
When requesting the scalefactor from Screen.AllScreen, the primary screen scalefactor is returned for all screens instead of the actual individual scale factors.

**Comment by enginkirmaci** [comment]
@JonasEmilDamsgaard you probably forget to set manifest file in your project setting. For example, check the test app csproj file.
https://github.com/micdenny/WpfScreenHelper/blob/master/test/WpfScreenHelper.DpiTestWpfApp/WpfScreenHelper.DpiTestWpfApp.csproj

**Comment by JonasEmilDamsgaard** [comment]
Hi @enginkirmaci. Thank you for the answer.

However, whether I reference WpfScreenHelper as a <ProjectReference> or a <PackageReference> it still returns the same wrong. The error seems to be at line 65 within ...\wpfscreenhelper-master\wpfscreenhelper-master\src\WpfScreenHelper\Screen.cs. Perhaps you would be so kind and spend a couple of minutes looking into it.

Thanks in advance.

**Comment by enginkirmaci** [comment]
I was having the same issue and I realized that I didn't set manifest file. In the meantime, I might change something. I'll check again and let you know.

**Comment by micdenny** [comment]
closed by #10

**Comment by micdenny** [comment]
[v2.0.0 has been released](https://www.nuget.org/packages/WpfScreenHelper/2.0.0)
